CREATE TABLE USER(
	ID_UTILISATEUR INTEGER AUTO§8INCREMENT GENERATED PRIMARY KEY,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	MAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL
);