CREATE DATABASE SEVENTHSXS7SKY;

CREATE TABLE USER(
	ID_UTILISATEUR INTEGER AUTO_INCREMENT,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	MAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_UTILISATEUR)
);

INSERT INTO `seventhsxs7sky`.`USER` (`ID_UTILISATEUR`, `FIRST_NAME`, `LAST_NAME`, `MAIL`, `PASSWORD`) VALUES (NULL, 'ADMIN', 'ADMIN', 'ADMIN@ADMIN.FR', 'ADMIN');